require: rubocop-rails

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30

Metrics/LineLength:
  Max: 130

Rails:
  Enabled: true

Rails/HttpStatus:
  Enabled: true
  EnforcedStyle: numeric

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MixinUsage:
  Exclude:
    - bin/setup

Style/RedundantReturn:
  AllowMultipleReturnValues: true

